name: Check database_setup_bool Setting

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check-db-setting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Print database_setup_bool settings
      run: |
        grep "database_setup_bool" src/LEA_Finance_Data_Visualizations_v2.ipynb

    - name: Check database_setup_bool value in Jupyter Notebook
      run: |
        if grep "database_setup_bool = True" src/LEA_Finance_Data_Visualizations_v2.ipynb; then
          echo "Error: database_setup_bool must be set to False before merging" >&2
          exit 1
        fi
